import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { BsInstagram, BsWhatsapp } from "react-icons/bs";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Farmabelen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>


        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/logo.png"
            alt="logo"
            width={350}
            height={150}
            priority
          />

        </div>
        <div className={styles.description}>
          <p>
            Estamos teniendo algunos inconvenientes, y ya estamos trabajando para solucionarlos.&nbsp;
            <code className={styles.code}>Estaremos nuevamente online pronto.</code>
          </p>
        </div>


        <div className={styles.grid}>

        <a 
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="enlaceEscondido"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://wa.me/+541131791202"
            className={styles.card}
            id="whatsapp"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              <BsWhatsapp/> Whatsapp <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="https://www.instagram.com/farma_belen/?hl=es"
            className={styles.card}
            id="instagram"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            <BsInstagram/> Instagram <span>-&gt;</span>
            </h2>

          </a>


          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="enlaceEscondido"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
